### ISSUE TITLE
Error writing characteristics

### ISSUE THREAD

**Issue by a01271588** [abc873693/Flutter-bluetooth#1]
Hi i keep getting this errors while pushing the first two buttons and connected to a BT device.
```
E/flutter (11069): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: Class '_ControllerSubscription<BluetoothDeviceState>' has no instance method 'writeCharacteristic'.
E/flutter (11069): Receiver: Instance of '_ControllerSubscription<BluetoothDeviceState>'
E/flutter (11069): Tried calling: writeCharacteristic("a", Instance(length:2) of '_GrowableList')
E/flutter (11069): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (11069): #1      _MyHomePageState.build.<anonymous closure> (package:bt_test/main.dart:65:24)
E/flutter (11069): <asynchronous suspension> 
```

**Comment by abc873693** [comment]
This app make by https://github.com/pauldemarco/flutter_blue.
I not sure your problem.
Maybe you no create class instance.
You can see library tutorial,or post your source project.
